name: rec_ball
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.7.0


dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.10.1
  cloud_firestore: ^5.6.2

  cupertino_icons: ^1.0.8
  http: ^1.3.0
  google_nav_bar: ^5.0.7
  intl: ^0.20.2
  firebase_auth: ^5.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - Images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: InriaSerif
      fonts:
        - asset: fonts/InriaSerif-Bold.ttf
          weight: 700
        - asset: fonts/InriaSerif-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/InriaSerif-Italic.ttf
          style: italic
        - asset: fonts/InriaSerif-Light.ttf
          weight: 300
        - asset: fonts/InriaSerif-LightItalic.ttf
          weight: 300 
          style: italic
        - asset: fonts/InriaSerif-Regular.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
